pipeline {
    agent any

    environment {
        // Set Terraform version if needed
        //TERRAFORM_VERSION = "1.5.7"
        // Optional: AWS credentials if Terraform will use AWS
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages {
        stage('Checkout') {
            steps {
                echo "Checking out code from GitHub..."
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                dir('terraform/e-commerce-cluster/environments/dev') {
                    echo "Initializing Terraform..."
                    sh "ls"
                    sh "pwd"
                    sh "terraform init"
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform/e-commerce-cluster/environments/dev') {
                    echo "Running Terraform plan..."
                    sh "terraform plan -out=tfplan"
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('terraform/e-commerce-cluster/environments/dev') {
                    echo "Applying Terraform changes..."
                    sh "terraform apply -auto-approve tfplan"
                }
            }
        }

        stage('Show Terraform Outputs') {
            steps {
                dir('terraform/e-commerce-cluster/environments/dev') {
                    echo "Printing Terraform outputs..."
                    sh "terraform output"
                }
            }
        }

        stage('Show Private IPs') {
            steps {
                dir('terraform/e-commerce-cluster/environments/dev') {
                    sh "terraform output private_ips"
                }
            }
        }
    }

    post {
        success {
            echo "Terraform applied successfully!"
        }
        failure {
            echo "Terraform run failed!"
        }
    }
}
