[ecommerce]
e-commerce-ec2-1 ansible_host=44.204.203.104 ansible_user=ec2-user
e-commerce-ec2-2 ansible_host=18.209.248.125 ansible_user=ec2-user

[postgres_primary]
e-commerce-ec2-1

[postgres_replica]
e-commerce-ec2-2