---
- name: Provision e-commerce EC2 instances
  hosts: ecommerce
  become: true
  vars:
    project_dir: /home/ec2-user/e-commerce-system
    postgres_user: ec2_user            # PostgreSQL role name (underscore because hyphen not allowed)
    postgres_password: "securepass"  # change this in production or use vault
  roles:
    #- database
    - application
