---
- name: Provision e-commerce EC2 instances
  hosts: ecommerce
  become: true
  vars:
    project_dir: /home/ec2-user/e-commerce-system
    postgres_user: ec2_user 
    postgres_password: "securepass"
  roles:
    - database
    - application
