apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: ecommerce
  labels:
    app: order-service
data:
  datasource.url: "jdbc:postgresql://postgres:5432/order_db"
  hibernate.ddl-auto: "update"
  hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
  product.service.url: "http://product-service:8081"
  spring.jpa.show-sql: "false"
  logging.level.root: "INFO"
  logging.level.com.ecommerce: "DEBUG"
