apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-service-config
  namespace: ecommerce
  labels:
    app: frontend-service
data:
  product.service.url: "http://product-service:8081"
  order.service.url: "http://order-service:8082"
  logging.level.root: "INFO"
  logging.level.com.ecommerce: "DEBUG"
