apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

commonLabels:
  app.kubernetes.io/name: frontend-service
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: frontend

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml

images:
  - name: ecommerce-frontend-service
    newTag: latest

replicas:
  - name: frontend-service
    count: 2
